[package]
name = "style-engine-demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
style-engine = { path = "../style-engine", version = "1.0.0" }
style-engine-vello = { path = "../style-engine-vello", version = "1.0.0" }
vello = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
image = { workspace = true }
pollster = "0.4"

[lints]
workspace = true
