[package]
name = "style-engine-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
style-engine = { path = "../style-engine" }
style-engine-soft = { path = "../style-engine-soft" }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
image = { workspace = true }
